// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset.sql

package database

import (
	"context"
)

const resetUserTable = `-- name: ResetUserTable :exec
DELETE FROM users
`

func (q *Queries) ResetUserTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUserTable)
	return err
}
